spring.application.name=contacomigo

spring.datasource.url=jdbc:postgresql://${DB_HOST}/contacomigo
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

api.security.token.secret=${JWT_SECRET_CC}

spring.jpa.hibernate.ddl-auto=validate